# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MI_Practical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MI_Practical
pod 'IQKeyboardManagerSwift', '~> 6.5'

end
